/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/premium`; params?: Router.UnknownInputParams; } | { pathname: `/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/terms`; params?: Router.UnknownInputParams; } | { pathname: `/../app_old/premium`; params?: Router.UnknownInputParams; } | { pathname: `/../app_old/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/../app_old/index`; params?: Router.UnknownInputParams; } | { pathname: `/../app_old/terms`; params?: Router.UnknownInputParams; } | { pathname: `/../app_old/profile`; params?: Router.UnknownInputParams; } | { pathname: `/../app_old/home`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/premium`; params?: Router.UnknownOutputParams; } | { pathname: `/privacy`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/terms`; params?: Router.UnknownOutputParams; } | { pathname: `/../app_old/premium`; params?: Router.UnknownOutputParams; } | { pathname: `/../app_old/privacy`; params?: Router.UnknownOutputParams; } | { pathname: `/../app_old/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../app_old/terms`; params?: Router.UnknownOutputParams; } | { pathname: `/../app_old/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/../app_old/home`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/premium${`?${string}` | `#${string}` | ''}` | `/privacy${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/terms${`?${string}` | `#${string}` | ''}` | `/../app_old/premium${`?${string}` | `#${string}` | ''}` | `/../app_old/privacy${`?${string}` | `#${string}` | ''}` | `/../app_old/index${`?${string}` | `#${string}` | ''}` | `/../app_old/terms${`?${string}` | `#${string}` | ''}` | `/../app_old/profile${`?${string}` | `#${string}` | ''}` | `/../app_old/home${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/premium`; params?: Router.UnknownInputParams; } | { pathname: `/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/terms`; params?: Router.UnknownInputParams; } | { pathname: `/../app_old/premium`; params?: Router.UnknownInputParams; } | { pathname: `/../app_old/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/../app_old/index`; params?: Router.UnknownInputParams; } | { pathname: `/../app_old/terms`; params?: Router.UnknownInputParams; } | { pathname: `/../app_old/profile`; params?: Router.UnknownInputParams; } | { pathname: `/../app_old/home`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
